// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjzepvoklqnubjpfqjoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqemVwdm9rbHFudWJqcGZxam96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDc0NjgsImV4cCI6MjA3MzE4MzQ2OH0.U8KnFTl3S9Osb18WMD8P62qbv9YwDSj3LlcU473lEaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});